version: "3.8"
services:
  fastapi_todo_auth_app:
    build: .
    container_name: ${WEB_HOST}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - .env
    entrypoint:
      - ./entrypoints/fastapi.sh
