name: todo_auth

on: [push, pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: pip install mypy

      - name: Format with flake8
        uses: actions/checkout@v4
      - uses: TrueBrain/actions-flake8@v2
        with:
          max_line_length: 100

      - name: Format with black
        uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "23.11.0"

      - name: Format with isort
        uses: davidslusser/actions_python_isort@v1.0.0
        with:
          options: "--check --diff --profile black --filter-files"

      - name: Typing with mypy
        run: mypy --explicit-package-base --ignore-missing-imports src/
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install poetry
        uses: snok/install-poetry@v1.0.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
