name: todo_auth

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#      - run: pip install black flake8 isort mypy pytest
      - uses: actions/checkout@v4
      - uses: TrueBrain/actions-flake8@v2
        with:
          max_line_length: 100
