name: todo_auth

on: push

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - run: pip install mypy
      - uses: actions/checkout@v4
      - uses: TrueBrain/actions-flake8@v2
        with:
          max_line_length: 100
      - run: mypy src
